# Generated by Django 3.1.14 on 2022-09-27 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=64)),
                ('third_id', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=64)),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('province', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('text', models.CharField(blank=True, max_length=1024, null=True)),
                ('enable', models.BooleanField(blank=True, null=True)),
                ('createdate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dynasty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stage', models.IntegerField()),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roleid', models.IntegerField()),
                ('level', models.IntegerField()),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dynasty', models.IntegerField()),
                ('desc', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('step_mode', models.IntegerField()),
                ('topic', models.CharField(blank=True, max_length=128, null=True)),
                ('describtion', models.CharField(blank=True, max_length=255, null=True)),
                ('tips', models.CharField(blank=True, max_length=255, null=True)),
                ('qtype', models.IntegerField(blank=True, null=True)),
                ('is_skip', models.BooleanField(blank=True, null=True)),
                ('op_1', models.CharField(blank=True, max_length=255, null=True)),
                ('op_2', models.CharField(blank=True, max_length=255, null=True)),
                ('op_3', models.CharField(blank=True, max_length=255, null=True)),
                ('op_4', models.CharField(blank=True, max_length=255, null=True)),
                ('correct', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StepMode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mode', models.IntegerField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerfyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=16)),
                ('code', models.IntegerField()),
                ('createdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('nike_name', models.CharField(blank=True, max_length=64, null=True)),
                ('header_res', models.CharField(blank=True, max_length=64, null=True)),
                ('body_res', models.CharField(blank=True, max_length=64, null=True)),
                ('max_score', models.IntegerField(blank=True, default=0, null=True)),
                ('cur_score', models.IntegerField(blank=True, default=0, null=True)),
                ('last_signed_time', models.DateTimeField(blank=True, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accountinfo')),
            ],
        ),
    ]
