# Generated by Django 3.2.6 on 2022-09-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=16)),
                ('describtion', models.CharField(max_length=16)),
                ('tips', models.CharField(max_length=16)),
                ('qtype', models.IntegerField()),
                ('an_1', models.CharField(max_length=128)),
                ('an_2', models.CharField(max_length=128)),
                ('an_3', models.CharField(max_length=128)),
                ('an_4', models.CharField(max_length=128)),
                ('correct', models.CharField(max_length=16)),
            ],
        ),
    ]
