# Generated by Django 3.2.6 on 2022-09-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roleinfo',
            old_name='last_step_id',
            new_name='last_step',
        ),
    ]
