# Generated by Django 3.2.6 on 2022-09-09 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='third_name',
        ),
    ]
