# Generated by Django 3.1.14 on 2022-09-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagesetting',
            name='uncorrect_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
